"""
Delta Exchange API Configuration & Endpoints
============================================
CRITICAL ARCHITECTURAL BOUNDARY:
Do NOT edit this file during generic frontend, UI, or database schema updates.
These URLs and environment mappings are strictly aligned with Delta Exchange infrastructure.
"""

from enum import Enum
from typing import Dict


class DeltaEnvironment(str, Enum):
    TESTNET = "testnet"
    MAINNET = "mainnet"
    TESTNET_INDIA = "testnet_india"
    MAINNET_INDIA = "mainnet_india"


# Canonical Delta Exchange REST API Base URLs
DELTA_BASE_URLS: Dict[str, str] = {
    DeltaEnvironment.TESTNET.value: "https://testnet-api.delta.exchange",
    DeltaEnvironment.MAINNET.value: "https://api.delta.exchange",
    DeltaEnvironment.TESTNET_INDIA.value: "https://cdn-ind.testnet.deltaex.org",
    DeltaEnvironment.MAINNET_INDIA.value: "https://api.india.delta.exchange",
}

# Network & Protocol Settings
DELTA_REQUEST_TIMEOUT_SECONDS: int = 10
DELTA_MAX_SIGNATURE_RETRY: int = 2
DELTA_USER_AGENT: str = "python-3.10"
